### PR TITLE
Update Index html

### PR DESCRIPTION
**Pull request by 7Wj9ncEz**
Add link tag for tag inside html that receive css

### CODE REVIEW

**Comment by 7Wj9ncEz** [comment]
Hi, how are you?

I trying help you

**Comment by jacob-beltran** [comment]
@7Wj9ncEz Hey! Thanks for taking a look. I decided to inline the styles for a couple reasons:
1.) There's not much styling going on
2.) It cuts down on a network request. On high-latency connections like mobile 3g or edge, that extra delay for an additional network request can cause a flash of un-styled content.

**Comment by 7Wj9ncEz** [comment]
Okay ;D

**Comment by 7Wj9ncEz** [comment]
I did not know that. That explains why some pens not equal in picture on my mobile device.

**Comment by 7Wj9ncEz** [comment]
Thanks ;D

**Pull request closed without merging**
